version: '3.8'

services:
  # Сервер WebSocket
  websocket:
    build: ./websocket-server
    container_name: websocket-server
    ports:
      - "8082:8082"
    networks:
      - demo-network
    environment:
      - NODE_ENV=production

  # Отправитель
  sender:
    build: ./sender
    container_name: demo-sender
    ports:
      - "8080:80"
    networks:
      - demo-network
    depends_on:
      - websocket
    environment:
      - WS_SERVER=websocket

  # Получатель
  receiver:
    build: ./receiver
    container_name: demo-receiver
    ports:
      - "8081:80"
    networks:
      - demo-network
    depends_on:
      - websocket
    environment:
      - WS_SERVER=websocket

networks:
  demo-network:
    driver: bridge