version: '3.8'

services:
  websocket:
    build: ./websocket-server
    container_name: websocket-server
    ports:
      - "8082:8082"
    networks:
      - demo-network

  sender:
    build: ./sender
    container_name: demo-sender
    ports:
      - "8080:80"
    volumes:
      - ./sender:/var/www/html  
    networks:
      - demo-network

  receiver:
    build: ./receiver
    container_name: demo-receiver
    ports:
      - "8081:80"
    volumes:
      - ./receiver:/var/www/html  
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge